
function(add_flag flag)
    add_compile_options("${flag}")
    message("Setting arch to ${flag}")
endfunction()

function(set_arch_impl linux_arch windows_arch)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        add_flag(${linux_arch})
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        add_flag(${linux_arch})
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        add_flag(${windows_arch})
    else()
        message(FATAL_ERROR "Not written for compiler ${CMAKE_CXX_COMPILER_ID}")
    endif()
endfunction()

function(set_arch arch_option)
    if (EMSCRIPTEN)
        set_arch_impl("-msimd128" "")
    elseif (${arch_option} STREQUAL "sse2")
        set_arch_impl("-msse2" "/arch:SSE2")
    elseif(${arch_option} STREQUAL "sse4_1")
        set_arch_impl("-msse4.1" "/arch:SSE2") # note -- no sse4.2
    elseif(${arch_option} STREQUAL "avx")
        set_arch_impl("-mavx" "/arch:AVX")
    elseif(${arch_option} STREQUAL "avx2")
        set_arch_impl("-mavx2" "/arch:AVX2")
    endif()
endfunction()